#!/usr/bin/env bash

# Written in 2022 by xf8b.
# To the extent possible under law, the author has dedicated all copyright and related and neighboring rights to this software to the public domain worldwide. This software is distributed without any warranty.
# See <https://creativecommons.org/publicdomain/zero/1.0> for a copy of the CC0 Public Domain Dedication.

# Notes:
# - the exit codes (`System.exit(exitCode);`) are:
#   - 0: shutdown
#   - 1: restart

while true; do
  echo "info: starting bot"
  ./bin/SuperTurtyBot
  
  exit_code=$?
  echo "info: bot stopped, checking exit code..."
  
  case $exit_code in
    1)
      echo "info: exit code 1"
      echo "info: restarting bot"
      ;;
    0)
      echo "info: exit code 0"
      echo "info: shutting down bot"
      break
      ;;
    *)
      echo "warning: unknown exit code, please modify this script to add functionality"
      echo "info: shutting down bot"
      break
      ;;
  esac
done
