name: Publish Site Docker Image to GitHub Packages

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: darealturtywurty/superturtybot-site

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: turtybotsite

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.1

      - name: Log in to the Container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build --no-cache -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest .

      - name: Push Docker image
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
